// 简易 Mock 数据库与延迟工具，用于无后端时的演示。
// 所有 Mock 调用会包装成 { code, message, data } 形式，与 client 拦截器一致。

import type { Store } from '@/types/store';
import type { PoultryCategory } from '@/types/poultry';
import type { InventoryItem } from '@/types/inventory';
import type { SalesOrder } from '@/types/order';
import type { ProcessingTask } from '@/types/processing';
import type { Supplier, PurchaseOrder, LossRecord } from '@/types/biz';
import type { Member, Staff, PricingItem, UserInfo } from '@/types/people';

export const sleep = (ms = 200) => new Promise((r) => setTimeout(r, ms));

let _id = 1000;
export const nextId = () => ++_id;

export const ok = <T>(data: T) => ({ code: 200, message: 'ok', data });

const today = (offsetDay = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDay);
  return d.toISOString().slice(0, 19).replace('T', ' ');
};

// ---------- 种子数据 ----------
export const stores: Store[] = [
  {
    id: 1,
    code: 'S001',
    name: '总店·城北店',
    address: '城北区幸福路 88 号',
    phone: '020-88880001',
    ownerName: '陈大壮',
    status: 'OPEN',
    openTime: '06:00',
    closeTime: '20:00',
    createdAt: today(-200),
  },
  {
    id: 2,
    code: 'S002',
    name: '城南旗舰店',
    address: '城南区菜市场 12 档',
    phone: '020-88880002',
    ownerName: '李美芳',
    status: 'OPEN',
    openTime: '05:30',
    closeTime: '21:00',
    createdAt: today(-150),
  },
  {
    id: 3,
    code: 'S003',
    name: '河西分店',
    address: '河西大道 56 号',
    phone: '020-88880003',
    ownerName: '王师傅',
    status: 'RENOVATING',
    openTime: '06:00',
    closeTime: '20:00',
    createdAt: today(-90),
  },
  {
    id: 4,
    code: 'S004',
    name: '高新区便民店',
    address: '高新区科技一路',
    phone: '020-88880004',
    ownerName: '赵建国',
    status: 'OPEN',
    openTime: '07:00',
    closeTime: '20:30',
    createdAt: today(-30),
  },
];

export const categories: PoultryCategory[] = [
  {
    id: 11,
    code: 'P001',
    name: '三黄鸡',
    species: '鸡',
    unit: 'JIN',
    basePrice: 18.8,
    processingFee: 3,
    avgWeight: 3.2,
    enabled: true,
    description: '本地散养，肉质紧实',
  },
  {
    id: 12,
    code: 'P002',
    name: '老母鸡',
    species: '鸡',
    unit: 'JIN',
    basePrice: 28.0,
    processingFee: 5,
    avgWeight: 4.5,
    enabled: true,
    description: '炖汤首选',
  },
  {
    id: 13,
    code: 'P003',
    name: '麻鸭',
    species: '鸭',
    unit: 'JIN',
    basePrice: 16.0,
    processingFee: 4,
    avgWeight: 5.0,
    enabled: true,
  },
  {
    id: 14,
    code: 'P004',
    name: '白条鹅',
    species: '鹅',
    unit: 'JIN',
    basePrice: 22.0,
    processingFee: 6,
    avgWeight: 7.5,
    enabled: true,
  },
  {
    id: 15,
    code: 'P005',
    name: '乳鸽',
    species: '鸽',
    unit: 'PIECE',
    basePrice: 35.0,
    processingFee: 2,
    avgWeight: 0.8,
    enabled: true,
  },
  {
    id: 16,
    code: 'P006',
    name: '鹌鹑',
    species: '鹌鹑',
    unit: 'PIECE',
    basePrice: 8.0,
    processingFee: 1,
    avgWeight: 0.3,
    enabled: true,
  },
  {
    id: 17,
    code: 'P007',
    name: '土兔',
    species: '兔',
    unit: 'JIN',
    basePrice: 32.0,
    processingFee: 8,
    avgWeight: 4.0,
    enabled: false,
  },
];

export const inventory: InventoryItem[] = [
  {
    id: 21,
    storeId: 1,
    storeName: '总店·城北店',
    categoryId: 11,
    categoryName: '三黄鸡',
    batchNo: 'B20260501-01',
    quantity: 86,
    avgWeight: 3.1,
    totalWeight: 266.6,
    health: 'HEALTHY',
    inStockAt: today(-2),
    supplierName: '广丰养殖',
  },
  {
    id: 22,
    storeId: 1,
    storeName: '总店·城北店',
    categoryId: 13,
    categoryName: '麻鸭',
    batchNo: 'B20260501-02',
    quantity: 40,
    avgWeight: 5.0,
    totalWeight: 200,
    health: 'HEALTHY',
    inStockAt: today(-1),
    supplierName: '广丰养殖',
  },
  {
    id: 23,
    storeId: 1,
    storeName: '总店·城北店',
    categoryId: 15,
    categoryName: '乳鸽',
    batchNo: 'B20260502-01',
    quantity: 120,
    avgWeight: 0.8,
    totalWeight: 96,
    health: 'OBSERVED',
    inStockAt: today(-1),
  },
  {
    id: 24,
    storeId: 2,
    storeName: '城南旗舰店',
    categoryId: 11,
    categoryName: '三黄鸡',
    batchNo: 'B20260430-03',
    quantity: 52,
    avgWeight: 3.2,
    totalWeight: 166.4,
    health: 'HEALTHY',
    inStockAt: today(-3),
  },
  {
    id: 25,
    storeId: 2,
    storeName: '城南旗舰店',
    categoryId: 14,
    categoryName: '白条鹅',
    batchNo: 'B20260430-04',
    quantity: 18,
    avgWeight: 7.5,
    totalWeight: 135,
    health: 'HEALTHY',
    inStockAt: today(-3),
  },
  {
    id: 26,
    storeId: 4,
    storeName: '高新区便民店',
    categoryId: 12,
    categoryName: '老母鸡',
    batchNo: 'B20260502-02',
    quantity: 28,
    avgWeight: 4.5,
    totalWeight: 126,
    health: 'HEALTHY',
    inStockAt: today(),
  },
];

export const orders: SalesOrder[] = [
  {
    id: 31,
    orderNo: 'SO20260508001',
    storeId: 1,
    storeName: '总店·城北店',
    cashierName: '陈小红',
    customerPhone: '13800001111',
    items: [
      {
        categoryId: 11,
        categoryName: '三黄鸡',
        quantity: 1,
        weight: 3.2,
        unitPrice: 18.8,
        processMethod: 'EVISCERATE',
        processFee: 3,
        subtotal: 3.2 * 18.8 + 3,
      },
    ],
    totalAmount: 3.2 * 18.8 + 3,
    discount: 0,
    payable: 3.2 * 18.8 + 3,
    payMethod: 'WECHAT',
    status: 'COMPLETED',
    createdAt: today(),
    paidAt: today(),
    completedAt: today(),
  },
  {
    id: 32,
    orderNo: 'SO20260508002',
    storeId: 1,
    storeName: '总店·城北店',
    cashierName: '陈小红',
    items: [
      {
        categoryId: 13,
        categoryName: '麻鸭',
        quantity: 2,
        weight: 9.8,
        unitPrice: 16,
        processMethod: 'CHOP',
        processFee: 8,
        subtotal: 9.8 * 16 + 8,
      },
      {
        categoryId: 15,
        categoryName: '乳鸽',
        quantity: 4,
        weight: 3.2,
        unitPrice: 35,
        processMethod: 'SLAUGHTER',
        processFee: 8,
        subtotal: 4 * 35 + 8,
      },
    ],
    totalAmount: 9.8 * 16 + 8 + 4 * 35 + 8,
    discount: 5,
    payable: 9.8 * 16 + 8 + 4 * 35 + 8 - 5,
    payMethod: 'CASH',
    status: 'PROCESSING',
    createdAt: today(),
    paidAt: today(),
  },
  {
    id: 33,
    orderNo: 'SO20260508003',
    storeId: 2,
    storeName: '城南旗舰店',
    cashierName: '李梅',
    items: [
      {
        categoryId: 14,
        categoryName: '白条鹅',
        quantity: 1,
        weight: 7.6,
        unitPrice: 22,
        processMethod: 'PACK',
        processFee: 6,
        subtotal: 7.6 * 22 + 6,
      },
    ],
    totalAmount: 7.6 * 22 + 6,
    discount: 0,
    payable: 7.6 * 22 + 6,
    status: 'PENDING',
    createdAt: today(),
  },
];

export const processingTasks: ProcessingTask[] = [
  {
    id: 41,
    taskNo: 'PT2026050801',
    orderNo: 'SO20260508002',
    storeName: '总店·城北店',
    categoryName: '麻鸭',
    quantity: 2,
    weight: 9.8,
    methods: ['SLAUGHTER', 'CHOP'],
    workerName: '老张',
    status: 'SLAUGHTERING',
    priority: 'NORMAL',
    createdAt: today(),
    startedAt: today(),
  },
  {
    id: 42,
    taskNo: 'PT2026050802',
    orderNo: 'SO20260508002',
    storeName: '总店·城北店',
    categoryName: '乳鸽',
    quantity: 4,
    weight: 3.2,
    methods: ['SLAUGHTER'],
    workerName: '老张',
    status: 'PLUCKING',
    priority: 'URGENT',
    createdAt: today(),
    startedAt: today(),
  },
  {
    id: 43,
    taskNo: 'PT2026050803',
    orderNo: 'SO20260507015',
    storeName: '总店·城北店',
    categoryName: '三黄鸡',
    quantity: 1,
    weight: 3.1,
    methods: ['SLAUGHTER', 'EVISCERATE'],
    workerName: '王师傅',
    status: 'PACKING',
    priority: 'NORMAL',
    createdAt: today(-1),
    startedAt: today(-1),
  },
  {
    id: 44,
    taskNo: 'PT2026050804',
    orderNo: 'SO20260508005',
    storeName: '城南旗舰店',
    categoryName: '白条鹅',
    quantity: 1,
    weight: 7.6,
    methods: ['SLAUGHTER', 'PACK'],
    status: 'WAIT_SLAUGHTER',
    priority: 'NORMAL',
    createdAt: today(),
  },
];

export const suppliers: Supplier[] = [
  {
    id: 51,
    name: '广丰养殖合作社',
    contact: '冯老板',
    phone: '13900000001',
    address: '从化区良口镇',
    category: '鸡/鸭',
    level: 'A',
    enabled: true,
  },
  {
    id: 52,
    name: '清远三黄鸡基地',
    contact: '黄经理',
    phone: '13900000002',
    address: '清远市清新区',
    category: '三黄鸡',
    level: 'A',
    enabled: true,
  },
  {
    id: 53,
    name: '惠州鹅厂',
    contact: '吴姐',
    phone: '13900000003',
    address: '惠州市博罗县',
    category: '鹅',
    level: 'B',
    enabled: true,
  },
  {
    id: 54,
    name: '番禺鸽场',
    contact: '何叔',
    phone: '13900000004',
    address: '番禺区石楼镇',
    category: '鸽/鹌鹑',
    level: 'A',
    enabled: true,
  },
];

export const purchases: PurchaseOrder[] = [
  {
    id: 61,
    orderNo: 'PO20260501001',
    supplierId: 51,
    supplierName: '广丰养殖合作社',
    storeId: 1,
    storeName: '总店·城北店',
    categoryName: '三黄鸡',
    quantity: 100,
    totalWeight: 320,
    unitPrice: 14,
    amount: 14 * 320,
    batchNo: 'B20260501-01',
    status: 'RECEIVED',
    createdAt: today(-3),
    receivedAt: today(-2),
  },
  {
    id: 62,
    orderNo: 'PO20260501002',
    supplierId: 51,
    supplierName: '广丰养殖合作社',
    storeId: 1,
    storeName: '总店·城北店',
    categoryName: '麻鸭',
    quantity: 50,
    totalWeight: 250,
    unitPrice: 11,
    amount: 11 * 250,
    batchNo: 'B20260501-02',
    status: 'RECEIVED',
    createdAt: today(-2),
    receivedAt: today(-1),
  },
  {
    id: 63,
    orderNo: 'PO20260507001',
    supplierId: 53,
    supplierName: '惠州鹅厂',
    storeId: 2,
    storeName: '城南旗舰店',
    categoryName: '白条鹅',
    quantity: 20,
    totalWeight: 150,
    unitPrice: 17,
    amount: 17 * 150,
    batchNo: 'B20260507-01',
    status: 'SUBMITTED',
    createdAt: today(-1),
  },
];

export const losses: LossRecord[] = [
  {
    id: 71,
    storeId: 1,
    storeName: '总店·城北店',
    categoryName: '乳鸽',
    batchNo: 'B20260502-01',
    quantity: 3,
    reason: 'DEAD',
    handler: '老张',
    disposeMethod: '无害化处理',
    occurredAt: today(-1),
  },
  {
    id: 72,
    storeId: 2,
    storeName: '城南旗舰店',
    categoryName: '麻鸭',
    batchNo: 'B20260430-05',
    quantity: 1,
    reason: 'SICK',
    handler: '李梅',
    disposeMethod: '深埋',
    occurredAt: today(-2),
  },
];

export const members: Member[] = [
  {
    id: 81,
    cardNo: 'M0001',
    name: '张阿姨',
    phone: '13800001111',
    level: 'GOLD',
    points: 1280,
    balance: 350,
    totalConsumption: 6800,
    registerStoreName: '总店·城北店',
    registeredAt: today(-180),
  },
  {
    id: 82,
    cardNo: 'M0002',
    name: '王伯伯',
    phone: '13800002222',
    level: 'SILVER',
    points: 560,
    balance: 80,
    totalConsumption: 2300,
    registerStoreName: '城南旗舰店',
    registeredAt: today(-90),
  },
  {
    id: 83,
    cardNo: 'M0003',
    name: '小李',
    phone: '13800003333',
    level: 'BRONZE',
    points: 120,
    balance: 0,
    totalConsumption: 480,
    registerStoreName: '高新区便民店',
    registeredAt: today(-30),
  },
];

export const staff: Staff[] = [
  {
    id: 91,
    name: '陈大壮',
    phone: '13900100001',
    role: 'MANAGER',
    storeId: 1,
    storeName: '总店·城北店',
    enabled: true,
    hireDate: today(-200),
  },
  {
    id: 92,
    name: '陈小红',
    phone: '13900100002',
    role: 'CASHIER',
    storeId: 1,
    storeName: '总店·城北店',
    enabled: true,
    hireDate: today(-180),
  },
  {
    id: 93,
    name: '老张',
    phone: '13900100003',
    role: 'BUTCHER',
    storeId: 1,
    storeName: '总店·城北店',
    enabled: true,
    hireDate: today(-300),
  },
  {
    id: 94,
    name: '王师傅',
    phone: '13900100004',
    role: 'BUTCHER',
    storeId: 1,
    storeName: '总店·城北店',
    enabled: true,
    hireDate: today(-150),
  },
  {
    id: 95,
    name: '李梅',
    phone: '13900100005',
    role: 'CASHIER',
    storeId: 2,
    storeName: '城南旗舰店',
    enabled: true,
    hireDate: today(-100),
  },
  {
    id: 96,
    name: '李美芳',
    phone: '13900100006',
    role: 'MANAGER',
    storeId: 2,
    storeName: '城南旗舰店',
    enabled: true,
    hireDate: today(-150),
  },
];

export const pricing: PricingItem[] = categories
  .filter((c) => c.enabled)
  .map((c, i) => ({
    id: 100 + i,
    categoryId: c.id,
    categoryName: c.name,
    date: today(),
    price: c.basePrice,
    processingFee: c.processingFee,
    promotionPrice: i % 3 === 0 ? c.basePrice * 0.9 : undefined,
  }));

export const adminUser: UserInfo = {
  id: 1,
  username: 'admin',
  nickname: '系统管理员',
  role: 'ADMIN',
  storeId: 1,
  storeName: '总店·城北店',
};
